
# Site settings
title: Ginkgo
subtitle: Microstructure imaging
#baseurl:
#url:
baseurl: ginkgo
url: https://iuszynski.github.io

# Contacts
email: ivy.uszynski@cea.fr
author:
street_address:
city:
state: 
zip_code:
country: France
phone:

# Index
short_desc: Mapping the brain microstructure accross individuals and species
long_desc: 'Within the framework of the transversal research program "Cyto in vivo", our main objective is twofold: mapping the cerebral structural connectome and mapping the cortex cytoarchitectony and myeloarchitectony at the individual scale, from animal to human using MRI. To this end, the scientific strategy is based on 3 pillars: the collection of extreme field (11.7 T, 17.2 T) MRI data acquired on post-mortem brains, the collection of ultra-high field (3 T, 7 T) MRI data acquired on human volunteers, and the development of innovative numerical methods of inference of the structural connectome, cytoarchitectonics and myeloarchitectonics of individual brains based on high performance computing (HPC), numerical simulation and artificial intelligence (AI).'
# Expiration in days
expiration_opportunities: 100
expiration_news: 370

# Social settings
500px_url: http://www.neurospin-wiki.org/pmwiki/Main/DirectionsToNeurospin
#facebook_url: https://www.facebook.com/pages/NeuroSpin/171075046414933
github_url: https://github.com/iuszynki
#twitter_url: https://twitter.com/neurospin_91
#youtube_url: https://www.youtube.com/CEASaclay
map_url: https://www.google.fr/maps/@48.720535,2.1467526,16z?hl=en

# Sass building
sass:
    sass_dir: _sass
    
# Build settings
markdown: kramdown

# Collections
collections_dir: _collections
collections:

  opportunities:
    output    : true
    permalink : /:collection/:path

  collaborators:
    output    : true
    permalink : /colleborators/:title/index.html

  people:
    output    : true
    permalink : /people/:title/index.html

  news:
    output    : true
    permalink : /news/:title/index.html

  biblio:
    output    : true
    permalink : /biblio/:title/index.html

  research:
    output    : true
    permalink : /research/:title/index.html

